local wk = require("which-key")
wk.add({
{ "<leader>0", desc = "last tab" },
{ "<leader>1", desc = "tab 1" },
{ "<leader>2", desc = "tab 2" },
{ "<leader>3", desc = "tab 3" },
{ "<leader>4", desc = "tab 4" },
{ "<leader>5", desc = "tab 5" },
{ "<leader>6", desc = "tab 6" },
{ "<leader>7", desc = "tab 7" },
{ "<leader>8", desc = "tab 8" },
{ "<leader>9", desc = "tab 9" },
{ "<leader>q", desc = "tab close" },
{ "<leader>Q", desc = "tab close!" },
{ "<leader>h", desc = "tab prev" },
{ "<leader>l", desc = "tab next" },
{ "<leader>v", desc = "vs" },

{ "<leader>m", desc = "top menu" },
{ "<leader>w", desc = "toggle wrap" },

{ "<leader>c", desc = "CSV+JSON" },
{ "<leader>cs", desc = "CSV" },
{ "<leader>cj", desc = "JSON" },
{ "<leader>csa", desc = "align CSV" },
{ "<leader>csA", desc = "clear CSV alignment" },
{ "<leader>[c", desc = "prev csv column" },
{ "<leader>]c", desc = "next csv column" },
{ "<leader>cja", desc = "format in jq" },
{ "<leader>cjj", desc = "set JSON filetype" },

{ "<leader>t", desc = "view files" },
{ "<leader>s", desc = "%s/…//g" },
{ "<leader>u", desc = "open url" },

--{ "<leader>d", desc = "duplicate file" },
--{ "<leader>p", desc = "toggle theme" },
--{ "<leader>z", desc = "floating terminal" },
--{ "<leader>f", desc = "fzf" },
--{ "<leader>g", desc = "grep" },
--{ "<leader>G", desc = "grep under cursor" },
--{ "<leader>x", desc = "chmod +x" },
--{ "<leader>R", desc = "reload config" },
--{ "<leader>vs", desc = "vsplit next buf" },
--{ "<leader>w", desc = "write" },
--{ "<leader>W", desc = "toggle wrap" },
--{ "<leader>q", desc = "close buf" },
--{ "<leader>Q", desc = "close buf!" },
--{ "<leader>U", desc = "close ALL buf" },
--{ "<leader>nn", desc = "toggle relative nums" },
--{ "<leader>H", desc = "htop terminal" },
--{ "<leader>T", desc = "git status" },
--{ "<leader>F", desc = "fzf opts" },
},
{ triggers = {
   { "<auto>", mode = "nixsotc" },
   { "a", mode = { "n" } },
 }
})
